---

services:
  squid:
    image: fisher772/squid
    container_name: squid
    hostname: squid
    restart: always
    ports:
      - '8888:8888'
      - '8889:8889'
    volumes:
      - cache:/var/spool/squid
      - logs:/var/log
      - data:/etc/squid
      - nginx_ssl:/etc/squid/ssl
    environment:
      - TZ=${EKB}
      - HTTP_PORT=${HTTP_PORT}
      - HTTPS_PORT=${HTTPS_PORT}
      - HTTPS_STATUS=${HTTPS_STATUS}
      - DNS_VALUE=${DNS}
      - SSL_CERT=${SSL_C}
      - SSL_KEY=${SSL_K}
      #- TRUSTED_IP=${T_IP}
    networks:
      - squid

networks:
  squid:
volumes:
  cache:
  logs:
  data:
  nginx_ssl:
